# Generated by Django 4.1.2 on 2022-10-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_uuid', models.CharField(max_length=100)),
                ('bot_welcome_message', models.CharField(max_length=100)),
                ('terms_url', models.CharField(max_length=100)),
                ('bot_name', models.CharField(max_length=100)),
                ('auto_login', models.CharField(max_length=100)),
                ('end_user_dialog_uuid', models.CharField(max_length=100)),
                ('helper_dialog_uuid', models.CharField(max_length=100)),
                ('b2c_enabled', models.CharField(max_length=100)),
                ('b2b_enabled', models.CharField(max_length=100)),
                ('is_top_bot', models.CharField(max_length=100)),
                ('bot', models.CharField(max_length=100)),
                ('company_id', models.CharField(max_length=100)),
            ],
        ),
    ]
