# Generated by Django 4.1.2 on 2022-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_industries_bot_industry_uuid_alter_bot_b2b_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='is_top_bot',
            field=models.BooleanField(default=False),
        ),
    ]
