# Generated by Django 4.1.2 on 2022-11-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bot_auto_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUserDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.CharField(max_length=100)),
                ('end_user_dialog_uuid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HelperDialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_uuid', models.CharField(max_length=100)),
                ('profile_icon_url', models.ImageField(blank=True, upload_to='images/')),
                ('widget_icon_url', models.ImageField(blank=True, upload_to='images/')),
                ('font_name', models.CharField(max_length=100)),
                ('background_color_code', models.CharField(max_length=100)),
                ('employee_text_color_code', models.CharField(max_length=100)),
                ('employee_background_color_code', models.CharField(max_length=100)),
                ('enduser_text_color_code', models.CharField(max_length=100)),
                ('enduser_background_color_code', models.CharField(max_length=100)),
                ('header_text_color_code', models.CharField(max_length=100)),
                ('header_background_color_code', models.CharField(max_length=100)),
                ('message_text_color_code', models.CharField(max_length=100)),
                ('message_background_color_code', models.CharField(max_length=100)),
                ('widget_toggle_color_code', models.CharField(max_length=100)),
                ('widget_width_code', models.CharField(max_length=100)),
                ('widgetJs', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='industry_uuid',
        ),
    ]
