# Generated by Django 4.1.2 on 2022-11-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_enduserdialog_helperdialog_widget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_width_code',
            field=models.CharField(default=400, max_length=100),
        ),
    ]
